{% set name = "centreseq" %}
  {% set version = "0.3.3" %}
  {% set sha256 = "84aeec69c385b10ac51e6f69e9d61f4772c41f94f5a9bd30793457691b85d8eb" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://github.com/BFSSI-Bioinformatics-Lab/centreseq/archive/v{{ version }}.zip
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 0
  entry_points:
    - centreseq=centreseq.centreseq_cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - biopython >=1.74
    - click >=7.0
    - pandas >=0.24.0
    - python >=3.6
    - scipy >=1.1
    - tqdm >=4.32.2
    - xlsxwriter >=1.1.8
    - seaborn >=0.9.0
    - pytest >=5.0.1
    - mmseqs2
    - muscle
    - prokka

test:
  imports:
    - centreseq
    - centreseq.bin
    - centreseq.bin.core
    - centreseq.bin.helpers
    - centreseq.bin.tree
    - centreseq.bin.visualizations
  commands:
    - centreseq --version

about:
  home: https://github.com/bfssi-forest-dussault/centreseq
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast generation of core genome from bacterial strains
  dev_url: https://github.com/BFSSI-Bioinformatics-Lab/centreseq

extra:
  recipe-maintainers:
    - bfssi-forest-dussault
  container:
    extended-base: true
